
#启动端口
server:
  port: 8080

#datasource
spring:
  datasource:
    username: root
    password: unitimes
    url: jdbc:mysql://127.0.0.1:3306/consults?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

#redis cache
  redis:
    host: 127.0.0.1
    port: 6379

#rabbitmq
#  rabbitmq:
#    host: 127.0.0.1
#    port: 15672
#    username: guest
#    password: guest

mybatis:
  mapperLocations: classpath:xml/*.xml

